/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kalkulator;

import javax.swing.JOptionPane;

/**
 *
 * @author feby
 */
public class Kalkulator extends javax.swing.JFrame {

    /**
     * Creates new form Kalkulator
     */    
    
    public Kalkulator() {
        initComponents();
        aktif(true);
        setTombol(true);        
    }
    
    private double[] getInputs() throws IllegalArgumentException {
        String nilaiPertamaStr = txtNilaiPertama.getText().trim();
        String nilaiKeduaStr = txtNilaiKedua.getText().trim();

        if (nilaiPertamaStr.isEmpty() || nilaiKeduaStr.isEmpty()) {
            throw new IllegalArgumentException("Input masih kosong.");
        }

        try {
            double nilaiPertama = Double.parseDouble(nilaiPertamaStr);
            double nilaiKedua = Double.parseDouble(nilaiKeduaStr);
            return new double[] { nilaiPertama, nilaiKedua };
        } catch (NumberFormatException e) {
            throw new IllegalArgumentException("Input harus berupa angka.");
        }
    }

    private double getSingleInput() throws IllegalArgumentException {
        String nilaiPertamaStr = txtNilaiPertama.getText().trim();

        if (nilaiPertamaStr.isEmpty()) {
            throw new IllegalArgumentException("Input masih kosong.");
        }

        try {
            return Double.parseDouble(nilaiPertamaStr);
        } catch (NumberFormatException e) {
            throw new IllegalArgumentException("Input harus berupa angka.");
        }
    }

    private void showResult(double hasil) {
        txtHasil.setText(Double.toString(hasil));
    }

    private void calculate(String operation) {
        try {
            double hasil = 0;
            double[] inputs;

            switch (operation) {
                case "Tambah":
                    inputs = getInputs();
                    hasil = inputs[0] + inputs[1];
                    break;
                case "Kurang":
                    inputs = getInputs();
                    hasil = inputs[0] - inputs[1];
                    break;
                case "Kali":
                    inputs = getInputs();
                    hasil = inputs[0] * inputs[1];
                    break;
                case "Pangkat":
                    inputs = getInputs();
                    hasil = Math.pow(inputs[0], inputs[1]);
                    break;
                case "Akar":
                    double input = getSingleInput();
                    hasil = Math.sqrt(input);
                    break;
            }
            
            showResult(hasil);
                
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), 
                    "Error", JOptionPane.ERROR_MESSAGE);
            
        }
    }
    
    //mengset aktif tidak isian data
    private void aktif(boolean x)
    {
        txtNilaiPertama.setEditable(x);
        txtNilaiKedua.setEditable(x);
    }
    
    private void setTombol(boolean t)
    {
        txtHasil.setEnabled(!t);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNilaiPertama = new javax.swing.JTextField();
        txtNilaiKedua = new javax.swing.JTextField();
        txtHasil = new javax.swing.JTextField();
        cmdTambah = new javax.swing.JButton();
        cmdKali = new javax.swing.JButton();
        cmdAkar = new javax.swing.JButton();
        cmdKurang = new javax.swing.JButton();
        cmdPangkat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Nilai Pertama");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Nilai Kedua");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Hasil");

        txtNilaiPertama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNilaiPertamaActionPerformed(evt);
            }
        });

        cmdTambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmdTambah.setText("Tambah");
        cmdTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdTambahActionPerformed(evt);
            }
        });

        cmdKali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmdKali.setText("Kali");
        cmdKali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdKaliActionPerformed(evt);
            }
        });

        cmdAkar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmdAkar.setText("Akar");
        cmdAkar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAkarActionPerformed(evt);
            }
        });

        cmdKurang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmdKurang.setText("Kurang");
        cmdKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdKurangActionPerformed(evt);
            }
        });

        cmdPangkat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmdPangkat.setText("Pangkat");
        cmdPangkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPangkatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(89, 89, 89)
                        .addComponent(txtHasil, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(40, 40, 40)
                        .addComponent(txtNilaiPertama))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(52, 52, 52)
                        .addComponent(txtNilaiKedua)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmdTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmdKurang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmdKali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmdAkar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmdPangkat))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNilaiPertama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdTambah))
                .addGap(5, 5, 5)
                .addComponent(cmdKali)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdKurang)
                    .addComponent(jLabel2)
                    .addComponent(txtNilaiKedua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdAkar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdPangkat)
                    .addComponent(jLabel3)
                    .addComponent(txtHasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNilaiPertamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNilaiPertamaActionPerformed
        
    }//GEN-LAST:event_txtNilaiPertamaActionPerformed

    private void cmdTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdTambahActionPerformed
        calculate("Tambah");
    }//GEN-LAST:event_cmdTambahActionPerformed

    private void cmdKaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdKaliActionPerformed
        calculate("Kali");
    }//GEN-LAST:event_cmdKaliActionPerformed

    private void cmdAkarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAkarActionPerformed
        calculate("Akar");
    }//GEN-LAST:event_cmdAkarActionPerformed

    private void cmdKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdKurangActionPerformed
        calculate("Kurang");
    }//GEN-LAST:event_cmdKurangActionPerformed

    private void cmdPangkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPangkatActionPerformed
        calculate("Pangkat");
    }//GEN-LAST:event_cmdPangkatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAkar;
    private javax.swing.JButton cmdKali;
    private javax.swing.JButton cmdKurang;
    private javax.swing.JButton cmdPangkat;
    private javax.swing.JButton cmdTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtHasil;
    private javax.swing.JTextField txtNilaiKedua;
    private javax.swing.JTextField txtNilaiPertama;
    // End of variables declaration//GEN-END:variables
}
